const constants = {
  FLUX: {
    TOGGLE_POPIN: 'TOGGLE_POPIN',
    UPDATE_VALUE: 'UPDATE_VALUE',
    SAVE_LOCALES: 'SAVE_LOCALES',
    IMPORT_LANGUAGES: 'IMPORT_LANGUAGES',
    CREATE_NEW_LANGUAGE: 'CREATE_NEW_LANGUAGE'
  },
  REACT: {
    NO_RENDER: false
  }
};

export default constants;
