const constants = {
  FLUX: {
    UPDATE_VALUE: 'UPDATE_VALUE',
    LOAD_LANGUAGES: 'LOAD_LANGUAGES',
    SAVE_LANGUAGES: 'SAVE_LANGUAGES',
    SAVE_LANGUAGES_DIFF: 'SAVE_LANGUAGES_DIFF',
    CREATE_NEW_LANGUAGE: 'CREATE_NEW_LANGUAGE'
  }
};

export default constants;
